# Generated by Django 4.2.11 on 2025-11-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "CENTRO",
                    models.TextField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                ("N_CENTRO", models.TextField(verbose_name="Nombre")),
                ("DIRECCION", models.TextField(verbose_name="Dirección")),
                ("POBLACION", models.TextField(verbose_name="Población")),
                ("PROVINCIA", models.TextField(verbose_name="Provincia")),
                ("POSTAL", models.TextField(verbose_name="Postal")),
                (
                    "EMAIL",
                    models.EmailField(default="", max_length=254, verbose_name="Email"),
                ),
                ("WWW", models.TextField(verbose_name="WWW")),
            ],
            options={
                "verbose_name": "Centro",
                "db_table": "dentfact_centro",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "SPCODE",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("COLEGIADO", models.CharField(blank=True, max_length=50, null=True)),
                ("DOCTOR", models.CharField(max_length=255)),
                ("I_APELLIDO", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "II_APELLIDO",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("NOMBRE", models.CharField(blank=True, max_length=255, null=True)),
                ("DNI", models.CharField(blank=True, max_length=50, null=True)),
                ("CIF", models.CharField(blank=True, max_length=255, null=True)),
                ("GASTOS", models.CharField(blank=True, max_length=5, null=True)),
                ("ESTADO", models.CharField(blank=True, max_length=255, null=True)),
                ("EMAIL", models.EmailField(blank=True, max_length=254, null=True)),
                ("DIRECCION", models.TextField(blank=True, null=True)),
                ("CIUDAD", models.CharField(blank=True, max_length=255, null=True)),
                ("POSTAL", models.CharField(blank=True, max_length=20, null=True)),
                ("TELEFONO", models.CharField(blank=True, max_length=50, null=True)),
                ("CUENTA", models.CharField(blank=True, max_length=255, null=True)),
                ("CODIGO", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ESPECIALIDAD",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "COLABORADOR",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("GABINETE_01", models.CharField(blank=True, max_length=5, null=True)),
                ("GABINETE_02", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "db_table": "dentfact_doctor",
            },
        ),
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "ESPECIALIDAD",
                    models.TextField(
                        primary_key=True, serialize=False, verbose_name="Especialidad"
                    ),
                ),
                ("DESCRIPCION", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Especialidad",
                "db_table": "dentfact_especialidad",
            },
        ),
        migrations.CreateModel(
            name="Factura_C",
            fields=[
                (
                    "FACTURA",
                    models.CharField(
                        default="Factura_default",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "L_DESDE",
                    models.CharField(default="Fecha desconocida", max_length=255),
                ),
                (
                    "L_HASTA",
                    models.CharField(default="Fecha desconocida", max_length=255),
                ),
                (
                    "SPCODE",
                    models.CharField(default="SPCODE desconocido", max_length=255),
                ),
                (
                    "DOCTOR",
                    models.CharField(default="Doctor desconocido", max_length=255),
                ),
                (
                    "ESPECIALIDAD",
                    models.CharField(
                        default="Especialidad desconocida", max_length=255
                    ),
                ),
                (
                    "COLABORADOR",
                    models.CharField(default="Colaborador desconocido", max_length=255),
                ),
                (
                    "COLEGIADO",
                    models.CharField(default="Colegiado desconocido", max_length=255),
                ),
                (
                    "I_APELLIDO",
                    models.CharField(default="I_APELLIDO desconocido", max_length=255),
                ),
                (
                    "II_APELLIDO",
                    models.CharField(default="II_APELLIDO desconocido", max_length=255),
                ),
                (
                    "NOMBRE",
                    models.CharField(default="NOMBRE desconocido", max_length=255),
                ),
                ("DNI", models.CharField(default="DNI desconocido", max_length=255)),
                (
                    "ESTADO",
                    models.CharField(default="Estado desconocido", max_length=255),
                ),
                (
                    "EMAIL",
                    models.CharField(default="E-mail desconocido", max_length=255),
                ),
                (
                    "DIRECCION",
                    models.CharField(default="Dirección desconocida", max_length=255),
                ),
                (
                    "CIUDAD",
                    models.CharField(default="Ciudad desconocida", max_length=255),
                ),
                (
                    "POSTAL",
                    models.CharField(default="Postal desconocida", max_length=255),
                ),
                (
                    "TELEFONO",
                    models.CharField(default="Teléfono desconocido", max_length=255),
                ),
                (
                    "CUENTA",
                    models.CharField(default="Cuenta desconocida", max_length=255),
                ),
                (
                    "CENTRO",
                    models.CharField(default="Centro desconocido", max_length=255),
                ),
                (
                    "N_CENTRO",
                    models.CharField(default="N_CENTRO desconocido", max_length=255),
                ),
                (
                    "SOCIEDAD",
                    models.CharField(default="Sociedad desconocida", max_length=255),
                ),
                ("CIF", models.CharField(default="CIF desconocida", max_length=255)),
                (
                    "DESCRIPCION_SOC",
                    models.CharField(default="Descripción desconocida", max_length=255),
                ),
                (
                    "DIRECCION_SOC",
                    models.CharField(default="Dirección desconocida", max_length=255),
                ),
                (
                    "POSTAL_SOC",
                    models.CharField(default="Postal desconocida", max_length=255),
                ),
                (
                    "PROVINCIA_SOC",
                    models.CharField(default="Provincia desconocida", max_length=255),
                ),
                (
                    "REPRESENTANTE",
                    models.CharField(
                        default="Representante desconocida", max_length=255
                    ),
                ),
                (
                    "NIF_REP",
                    models.CharField(default="NIF desconocida", max_length=255),
                ),
                (
                    "LIQUIDACION",
                    models.CharField(default="Liquidación desconocida", max_length=255),
                ),
                ("HHRR", models.CharField(default="HHRR desconocida", max_length=255)),
                ("NETO", models.CharField(default="0", max_length=255)),
                ("BRUTO", models.CharField(default="0", max_length=255)),
                ("PORCENTAJE", models.CharField(default="0", max_length=255)),
                ("GASTOS", models.CharField(default="0", max_length=255)),
                ("IRPF", models.CharField(default="0", max_length=255)),
                ("CALCULO", models.CharField(default="Cálculo", max_length=255)),
            ],
            options={
                "verbose_name": "Factura_C",
                "db_table": "dentfact_factura_c",
            },
        ),
        migrations.CreateModel(
            name="Factura_D",
            fields=[
                (
                    "FACTURA",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("MES", models.CharField(blank=True, max_length=2, null=True)),
                ("ANNO", models.CharField(blank=True, max_length=4, null=True)),
                ("EMISION", models.CharField(blank=True, max_length=10, null=True)),
                ("SPCODE", models.CharField(blank=True, max_length=6, null=True)),
                ("DOCTOR", models.CharField(blank=True, max_length=6, null=True)),
                ("DNI", models.CharField(blank=True, max_length=255, null=True)),
                ("COLEGIADO", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "COLABORADOR",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("EMAIL", models.CharField(blank=True, max_length=255, null=True)),
                ("TELEFONO", models.CharField(blank=True, max_length=255, null=True)),
                ("DIRECCION", models.CharField(blank=True, max_length=255, null=True)),
                ("CUENTA", models.CharField(blank=True, max_length=255, null=True)),
                ("ESTADO", models.CharField(blank=True, max_length=255, null=True)),
                ("CIF", models.CharField(blank=True, max_length=255, null=True)),
                ("SOCIEDAD", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "DESCRIPCION_SOC",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "DIRECCION_SOC",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("POSTAL_SOC", models.CharField(blank=True, max_length=255, null=True)),
                ("CIUDAD", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "REPRESENTANTE",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("NIF_REP", models.CharField(blank=True, max_length=255, null=True)),
                ("GASTOS", models.CharField(blank=True, max_length=255, null=True)),
                ("IRPF", models.CharField(blank=True, max_length=255, null=True)),
                ("CUOTA_IRPF", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "TOTAL_FACTURA",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "BASE_FACTURA",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "BRUTO_TOTAL",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("CALCULO", models.CharField(blank=True, max_length=255, null=True)),
                ("PORCENTAJE", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "CALCULO_TOTAL",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("L_DESDE", models.CharField(blank=True, max_length=10, null=True)),
                ("L_HASTA", models.CharField(blank=True, max_length=10, null=True)),
                ("I_APELLIDO", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "II_APELLIDO",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("NOMBRE", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ESPECIALIDAD",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("CODIGO", models.CharField(blank=True, max_length=255, null=True)),
                ("POSTAL", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "PROVINCIA_SOC",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "LIQUIDACION",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("HHRR", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "dentfact_factura_d",
            },
        ),
        migrations.CreateModel(
            name="Factura_R",
            fields=[
                (
                    "FACTURA",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("FECHA", models.CharField(max_length=255)),
                ("PERIODO", models.CharField(max_length=255)),
                ("CIF", models.CharField(max_length=255)),
                ("DESCRIPCION_SOC", models.CharField(max_length=255)),
                ("DIRECCION_SOC", models.CharField(max_length=255)),
                ("POSTAL_SOC", models.CharField(max_length=255)),
                ("CENTRO", models.CharField(max_length=255)),
                ("CENTRO_N", models.CharField(max_length=255)),
                ("SUBTOTAL", models.CharField(max_length=255)),
                ("TOTAL", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "dentfact_factura_r",
            },
        ),
        migrations.CreateModel(
            name="Importes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("SPCODE", models.CharField(max_length=10)),
                ("CENTRO", models.CharField(max_length=4)),
                ("N_CENTRO", models.CharField(blank=True, max_length=100, null=True)),
                ("ESPECIALIDAD", models.CharField(max_length=100)),
                ("DOCTOR", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "COLABORADOR",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("COLEGIADO", models.CharField(blank=True, max_length=10, null=True)),
                ("CIF", models.CharField(blank=True, max_length=15, null=True)),
                ("LIQUIDACION", models.CharField(blank=True, max_length=20, null=True)),
                ("L_DESDE", models.CharField(blank=True, max_length=10, null=True)),
                ("L_HASTA", models.CharField(blank=True, max_length=10, null=True)),
                ("PP_BASE", models.CharField(blank=True, max_length=10, null=True)),
                ("PP_LIQUIDO", models.CharField(blank=True, max_length=10, null=True)),
                ("PM_BASE", models.CharField(blank=True, max_length=10, null=True)),
                ("PM_LIQUIDO", models.CharField(blank=True, max_length=10, null=True)),
                ("P_BASE", models.CharField(blank=True, max_length=10, null=True)),
                ("P_LIQUIDO", models.CharField(blank=True, max_length=10, null=True)),
                ("R_BASE", models.CharField(blank=True, max_length=10, null=True)),
                ("R_LIQUIDO", models.CharField(blank=True, max_length=10, null=True)),
                ("C_FIJA", models.CharField(blank=True, max_length=10, null=True)),
                ("C_TURNO", models.CharField(blank=True, max_length=10, null=True)),
                ("PPA_BASE", models.CharField(blank=True, max_length=10, null=True)),
                ("PPA_LIQUIDO", models.CharField(blank=True, max_length=10, null=True)),
                ("PMA_BASE", models.CharField(blank=True, max_length=10, null=True)),
                ("PMA_LIQUIDO", models.CharField(blank=True, max_length=10, null=True)),
                ("PA_BASE", models.CharField(blank=True, max_length=10, null=True)),
                ("PA_LIQUIDO", models.CharField(blank=True, max_length=10, null=True)),
                ("HHRR", models.CharField(blank=True, max_length=10, null=True)),
                ("BRUTO", models.CharField(blank=True, max_length=10, null=True)),
                ("NETO", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "dentfact_importes",
            },
        ),
        migrations.CreateModel(
            name="Sociedad",
            fields=[
                ("ID_SOC", models.AutoField(primary_key=True, serialize=False)),
                ("CIF", models.TextField(default="", verbose_name="CIF")),
                ("SOCIEDAD", models.TextField(default="", verbose_name="Nombre")),
                (
                    "DESCRIPCION_SOC",
                    models.TextField(default="", verbose_name="Descripción"),
                ),
                (
                    "DIRECCION_SOC",
                    models.TextField(verbose_name="Dirección de la Sociedad"),
                ),
                (
                    "POSTAL_SOC",
                    models.TextField(verbose_name="Código Postal de la Sociedad"),
                ),
                (
                    "PROVINCIA_SOC",
                    models.TextField(verbose_name="Provincia de la Sociedad"),
                ),
                (
                    "REPRESENTANTE",
                    models.TextField(verbose_name="Representante de la Sociedad"),
                ),
                ("NIF_REP", models.TextField(verbose_name="NIF del Representante")),
            ],
            options={
                "verbose_name": "Sociedad",
                "db_table": "dentfact_sociedad",
            },
        ),
        migrations.CreateModel(
            name="Docpercent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ESPECIALIDAD", models.TextField(verbose_name="Especialidad")),
                ("CENTRO", models.TextField(verbose_name="Centro")),
                (
                    "IRPF",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="IRPF",
                    ),
                ),
                (
                    "PORCENTAJE",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="PORCENTAJE",
                    ),
                ),
                (
                    "SPCODE",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.doctor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Docpercent",
                "db_table": "dentfact_docpercent",
            },
        ),
        migrations.CreateModel(
            name="Factura_V",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Identificador único autogenerado para el registro.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qr_code",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contenido del código QR (DNI|FACTURA|FECHA_EMISION|TOTAL_FACTURA).",
                    ),
                ),
                (
                    "qr_base64",
                    models.TextField(
                        blank=True, help_text="Código QR en formato base64", null=True
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        default="",
                        help_text="Hash SHA-256 de la factura para verificación.",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        default="",
                        help_text="Hash SHA-256 de la factura anterior en la cadena.",
                        max_length=64,
                    ),
                ),
                (
                    "sif_id",
                    models.CharField(
                        help_text="Identificador único del Sistema Inmediato de Facturación (SIF).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "xml",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="XML generado para la factura según el esquema SIF-GE.",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        db_column="factura",
                        help_text="Factura asociada en la tabla dentfact_factura_d.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifactu_entries",
                        to="home.factura_d",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura_V",
                "verbose_name_plural": "Facturas_V",
                "db_table": "dentfact_factura_v",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["sif_id"], name="dentfact_fa_sif_id_ea6e52_idx"
                    ),
                    models.Index(
                        fields=["factura"], name="dentfact_fa_factura_bf9b14_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="factura_v",
            constraint=models.UniqueConstraint(
                fields=("sif_id",), name="unique_sif_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="docpercent",
            constraint=models.UniqueConstraint(
                fields=("SPCODE", "ESPECIALIDAD", "CENTRO"),
                name="unique_spcode_especialidad_centro",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="docpercent",
            unique_together={("SPCODE", "ESPECIALIDAD", "CENTRO")},
        ),
    ]
