# Generated by Django 4.2.11 on 2025-11-10 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_auto_20251109_1116"),
    ]

    operations = []
