# Generated by Django 4.2.11 on 2025-11-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_auto_20251110_1456"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factura_v",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="factura_v",
            name="unique_sif_id",
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="factura",
            field=models.ForeignKey(
                db_column="factura",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifactu_entries",
                to="home.factura_d",
            ),
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="hash",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="previous_hash",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="qr_base64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="qr_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="sif_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="factura_v",
            name="xml",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterUniqueTogether(
            name="factura_v",
            unique_together={("factura",)},
        ),
        migrations.AddIndex(
            model_name="factura_v",
            index=models.Index(fields=["hash"], name="dentfact_fa_hash_81778c_idx"),
        ),
    ]
