# Generated by Django 4.2.11 on 2025-11-11 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_factura_v_options_and_more"),
    ]

    operations = []
