# Generated by Django 4.2.11 on 2025-11-11 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_auto_20251111_1027"),
    ]

    operations = []
