# Generated by Django 4.2.11 on 2025-11-11 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_auto_20251111_1028"),
    ]

    operations = []
