# Generated by Django 4.2.11 on 2025-11-11 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_auto_20251111_1052"),
    ]

    operations = []
