# Generated by Django 4.2.11 on 2025-11-11 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_auto_20251111_1156"),
    ]

    operations = []
