# Generated by Django 4.2.11 on 2025-11-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_auto_20251111_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura_v",
            name="factura",
            field=models.ForeignKey(
                db_column="factura",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifactu_entries",
                to="home.factura_d",
            ),
        ),
    ]
