# Generated by Django 4.2.11 on 2025-11-11 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_factura_v_factura"),
    ]

    operations = []
