# Generated by Django 4.2.11 on 2025-11-11 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_auto_20251111_1337"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factura_d",
            options={},
        ),
    ]
