# Generated by Django 6.1.1 on 2026-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_factura_d_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DOCTOR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
