# Generated by Django 6.1.1 on 2026-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_doctor_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_d',
            name='DOCTOR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factura_d',
            name='POSTAL',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factura_d',
            name='POSTAL_SOC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
